// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        ); 
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7A19mBT1QMJ-dXoDJ-LYcDcdbrb5PIn8',
    appId: '1:281929860292:web:ac82981ffb8dc1b0d27591',
    messagingSenderId: '281929860292',
    projectId: 'koyum-64efd',
    authDomain: 'koyum-64efd.firebaseapp.com',
    databaseURL: 'https://koyum-64efd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'koyum-64efd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKWd4LRptqbt8fcIFCSFlGaU6-j09aR5I',
    appId: '1:281929860292:android:06a08c06b417ab8bd27591',
    messagingSenderId: '281929860292',
    projectId: 'koyum-64efd',
    databaseURL: 'https://koyum-64efd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'koyum-64efd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNyZAfn8kxt633DXYm17-DBKmPTolQwyA',
    appId: '1:281929860292:ios:f89af2be9ea8da52d27591',
    messagingSenderId: '281929860292',
    projectId: 'koyum-64efd',
    databaseURL: 'https://koyum-64efd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'koyum-64efd.appspot.com',
    iosClientId: '281929860292-orjpcpl1pu75jnjumol1s9h9tne1ds8d.apps.googleusercontent.com',
    iosBundleId: 'com.loremipsum.koyum.koyum',
  );
}
